apiVersion: v2
name: librarian
description: librarian Argo CD Apps of Apps for kast
version: 1.4.0
home: https://github.com/kast-spells
sources:
  - https://github.com/kast-spells/kast-release
maintainers:
  - name: namen malkav
    email: namenmalkav@gmail.com
  - name: laaledesiempre
    email: laaledesiempre@disroot.org