{{/*kast - Kubernetes arcane spelling technology
Copyright (C) 2023 namenmalkv@gmail.com
Licensed under the GNU GPL v3. See LICENSE file for details.
## TODO extend the spec dinamicly
 */}}
{{ if not .Values.projectDisabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ default (default $.Release.Name $.Values.name ) $.Values.projectName }}
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{- end }}